### ISSUE TITLE
Library functions

### ISSUE THREAD

**Issue by faheem4797** [JoshMunstermann/payfast#1]
Sorry if this seems like a silly question.

But does this library generates the uri for us and then we can send an http request based on that uri and wait for response from payfast server and procced further?

Or does this library sends the http requests as well?

**Comment by JoshMunstermann** [comment]
Hi,

So it just generates the uri and creates the payment type on the payfast
server, there is no response from the server received(I was planning to
implement it at some point but haven't had the time).
(Also, please note that the README file is outdated, refer to the example
code)

Kind regards,
Josh.

**Comment by faheem4797** [comment]
@JoshMunstermann thanks. much appreciated.

**Comment by JoshMunstermann** [comment]
@faheem4797 I have recently updated the README and was review the codebase, I was mistaken when saying that there is no response from the server, it can be simulated(I tested it in sandbox) when using [ngrok](https://ngrok.com/docs/getting-started), please refer to [this](https://developers.payfast.co.za/docs#step_4_confirm_payment)
